name: Send Slack

on:
  push:
    branches:
      - master

env:
  SLACK_WEBHOOK: ${{ secrets.TODAY_DEVELOP_SLACK_WEBHOOK }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check env
        run: echo "webhook = ${{ env.SLACK_WEBHOOK }}"

      - name: Slack notification
        env:
          SLACK_WEBHOOK: ${{ env.SLACK_WEBHOOK }}
        uses: Ilshidur/action-slack@2.0.2
        with:
          args: '보리집사 오개완\n ${{ github.event.head_commit.message }}'
